packages:
  - packages/*
  - website
catalog:
  '@simple-libs/stream-utils': ^2.0.0
  '@types/semver': ^7.5.8
  meow: ^14.0.0
  semver: ^7.5.2
autoInstallPeers: false
allowBuilds:
  esbuild: true
  sharp: true
  simple-git-hooks: true
minimumReleaseAgeExclude:
  - '@simple-libs/hosted-git-info@2.0.0'
  - '@simple-libs/normalize-package-data@1.0.0'
  - '@simple-libs/child-process-utils@2.0.0'
  - '@simple-libs/stream-utils@2.0.0'
  - astro@7.0.4
