packages:
  - packages/*
catalog:
  '@simple-libs/stream-utils': ^1.2.0
  '@types/semver': ^7.5.8
  compare-func: ^2.0.0
  meow: ^13.0.0
  semver: ^7.5.2
onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
autoInstallPeers: false
