on: workflow_dispatch
name: manual-release-submodule
jobs:
  release-conventional-changelog-writer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://external-dot-oss-automation.appspot.com/'
          cache: 'pnpm'
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          pnpm publish --filter conventional-changelog-writer --no-git-checks --access public
  release-conventional-changelog-preset-loader:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://external-dot-oss-automation.appspot.com/'
          cache: 'pnpm'
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          pnpm publish --filter conventional-changelog-preset-loader --no-git-checks --access public
