on: workflow_dispatch
name: manual-release-submodule
jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - conventional-changelog-writer
          - conventional-changelog-preset-loader
          - conventional-recommended-bump
          - conventional-changelog
          - conventional-changelog-cli
          - standard-changelog
          - gulp-conventional-changelog
          - conventional-changelog-core
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: 'https://external-dot-oss-automation.appspot.com/'
          cache: 'pnpm'
      - name: publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          pnpm install
          pnpm publish --filter ${{ matrix.package }} --no-git-checks --access public
