on:
  push:
    branches:
      - master
name: release-please-submodule
jobs:
  changeFinder:
    runs-on: ubuntu-latest
    outputs:
      nodePaths: ${{ steps.interrogate.outputs.nodePaths }}
    steps:
      - uses: actions/checkout@v2
      - id: interrogate
        uses: actions/github-script@v4
        with:
            github-token: ${{secrets.GITHUB_TOKEN}}
            script: |
              const {execSync} = require('child_process');
              const [owner, repo] = process.env.GITHUB_REPOSITORY.split('/');
              const latestRelease = await github.repos.getLatestRelease({
                owner,
                repo
              });
              console.log(`latest release: ${JSON.stringify(latestRelease.data)}`);
              execSync('git pull --tags');
              execSync(`git reset --hard ${latestRelease.data.tag_name}`);
              const status = execSync(`git diff --name-only origin/master`, { encoding: 'utf-8'});
              console.log(status);
              const changes = status.split('\n');
              let nodePaths = new Set();
              for (const change of changes) {
                if (change.startsWith('packages/')) {
                    const library = change.split('/')[1];
                    nodePaths.add(library);
                };
              }
              nodePaths = Array.from(nodePaths);
              console.log(`::set-output name=nodePaths::${JSON.stringify(nodePaths)}`);
  release-pr:
    runs-on: ubuntu-latest
    needs: changeFinder
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.changeFinder.outputs.nodePaths)}}
    steps:
      - uses: google-github-actions/release-please-action@1f461f4ce9942f0541c795b0562ae01bb9c49d4c
        id: release-please
        with:
           path: packages/${{ matrix.package }}
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: node
           package-name: ${{ matrix.package }}
           monorepo-tags: true
           command: release-pr
  release-please-release:
    runs-on: ubuntu-latest
    needs: changeFinder
    strategy:
      fail-fast: false
      matrix:
        package: ${{fromJson(needs.changeFinder.outputs.nodePaths)}}
    steps:
      - uses: GoogleCloudPlatform/release-please-action@1f461f4ce9942f0541c795b0562ae01bb9c49d4c
        id: tag-release
        with:
          path: packages/${{ matrix.package }}
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          monorepo-tags: true
          package-name: ${{ matrix.package }}
          command: github-release
      - uses: actions/checkout@v2
        if: ${{ steps.tag-release.outputs.release_created }}
      - uses: actions/setup-node@v1
        if: ${{ steps.tag-release.outputs.release_created }}
        with:
          node-version: 14
          registry-url: 'https://external-dot-oss-automation.appspot.com/'
      - name: publish
        if: ${{ steps.tag-release.outputs.release_created }}
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        run: |
          cd packages/${{ matrix.package }}
          npm install
          npm publish --access=public
