name: Tests
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
jobs:
  types:
    runs-on: ubuntu-latest
    name: types
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Check types
        run: pnpm test:types
  lint:
    runs-on: ubuntu-latest
    name: lint
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint files
        run: pnpm lint
  unit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 18
          - 20
    name: Node.js ${{ matrix.node-version }} / unit
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: git config --global user.name 'CI'
      - run: git config --global user.email 'dummy@example.org'
      - name: Run tests
        run: pnpm test:unit
      - name: Collect coverage
        uses: coverallsapp/github-action@main
        with:
          flag-name: actions ${{ matrix.node-version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          fail-on-error: false
  unit-windows:
    runs-on: windows-latest
    name: Windows / unit
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - run: git config --global user.name 'CI'
      - run: git config --global user.email 'dummy@example.org'
      - name: Run tests
        run: pnpm test:unit -- --test-timeout=60000
      - name: Collect coverage
        uses: coverallsapp/github-action@main
        with:
          flag-name: actions windows
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel: true
          fail-on-error: false
  finish:
    needs: [unit, unit-windows]
    runs-on: ubuntu-latest
    steps:
      - name: Upload collected coverage
        uses: coverallsapp/github-action@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
